name: Deploy API to Cloud Run

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/api/**'
      - '.github/workflows/deploy-api.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        
    - name: Configure Docker for GCR
      run: gcloud auth configure-docker
      
    - name: Build and push Docker image
      run: |
        cd apps/api
        IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/competitor-analysis-api"
        
        # Build with cache optimization
        docker build -t ${IMAGE_NAME}:latest .
        docker push ${IMAGE_NAME}:latest
        
    - name: Deploy to Cloud Run (FREE TIER)
      run: |
        gcloud run deploy competitor-analysis-api \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/competitor-analysis-api:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --concurrency 100 \
          --timeout 60s \
          --cpu-throttling \
          --no-use-http2 \
          --execution-environment gen2 \
          --set-env-vars="ASPNETCORE_ENVIRONMENT=Production"
          
    - name: Get service URL
      id: get-url
      run: |
        SERVICE_URL=$(gcloud run services describe competitor-analysis-api --platform managed --region us-central1 --format="value(status.url)")
        echo "service_url=$SERVICE_URL" >> $GITHUB_OUTPUT
        
    - name: Test deployment
      run: |
        SERVICE_URL=${{ steps.get-url.outputs.service_url }}
        
        # Wait for service to be ready
        sleep 30
        
        # Test health endpoint
        curl -f "$SERVICE_URL/api/health" || exit 1
        
        echo "✅ API deployment successful!"
        echo "🔗 Health check: $SERVICE_URL/api/health"
        echo "📡 API status: $SERVICE_URL/api/health/status"
        
    - name: Comment deployment URL
      uses: actions/github-script@v7
      if: github.event_name == 'push'
      with:
        script: |
          const serviceUrl = '${{ steps.get-url.outputs.service_url }}';
          
          github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha,
            body: `🚀 API deployed to Cloud Run: ${serviceUrl}`
          });
          
    - name: Usage reminder
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🆓 Remember: Cloud Run free tier includes:"
        echo "   - 2M requests/month"
        echo "   - 180K vCPU-seconds/month"
        echo "   - 360K GiB-seconds/month"
        echo "   - 1GB/month egress"
        echo "📊 Monitor usage at: https://console.cloud.google.com/run" 