name: Deploy API to Google Cloud Run (Main)

on:
  workflow_call:
    outputs:
      deployment_url:
        description: "API deployment URL"
        value: ${{ jobs.deploy.outputs.deployment_url }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      deployment_url: ${{ steps.deploy.outputs.deployment_url }}
    
    steps:
      - name: 🛒 Checkout Repository
        uses: actions/checkout@v4
      
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/api/github/package-lock.json
      
      - name: 📥 Install API Dependencies
        run: |
          cd apps/api/github
          npm ci
      
      - name: 🔧 Build API
        run: |
          cd apps/api/github
          npm run build
      
      - name: 🧪 Run API Tests
        run: |
          cd apps/api/github
          npm test 2>/dev/null || echo "⚠️ Tests not configured or failed"
      
      - name: 🔐 Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: 🛠️ Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: 🔍 Validate GCP Authentication & Permissions
        run: |
          echo "=== 🔐 VALIDATING GCP AUTHENTICATION ==="
          
          # Test basic authentication
          echo "🧪 Testing basic gcloud auth..."
          if gcloud auth list --filter=status:ACTIVE --format="value(account)"; then
            echo "✅ Successfully authenticated to GCP"
          else
            echo "❌ GCP authentication failed"
            exit 1
          fi
          
          # Verify project access
          echo "🏗️ Testing project access..."
          PROJECT_ID=$(gcloud config get-value project)
          echo "📋 Current project: $PROJECT_ID"
          
          if [ "$PROJECT_ID" != "${{ secrets.GCP_PROJECT_ID }}" ]; then
            echo "❌ Project mismatch! Expected: ${{ secrets.GCP_PROJECT_ID }}, Got: $PROJECT_ID"
            exit 1
          fi
          
          # Test service account details
          echo "👤 Service account details:"
          gcloud auth list --filter=status:ACTIVE --format="table(account,status)"
          
          echo "=== 📦 VALIDATING ARTIFACT REGISTRY ==="
          
          # Check if Artifact Registry API is enabled
          echo "🔌 Checking Artifact Registry API..."
          if gcloud services list --enabled --filter="name:artifactregistry.googleapis.com" --format="value(name)"; then
            echo "✅ Artifact Registry API is enabled"
          else
            echo "❌ Artifact Registry API is not enabled"
            exit 1
          fi
          
          # Check if repository exists
          echo "📦 Checking api-images repository..."
          if gcloud artifacts repositories describe api-images --location=us-central1 --format="value(name)"; then
            echo "✅ api-images repository exists"
          else
            echo "❌ api-images repository does not exist"
            echo "🔧 Creating repository..."
            gcloud artifacts repositories create api-images \
              --repository-format=docker \
              --location=us-central1 \
              --description="API Docker images for production deployment"
          fi
          
          # Test Docker authentication
          echo "🐳 Testing Docker authentication..."
          if gcloud auth configure-docker us-central1-docker.pkg.dev --quiet; then
            echo "✅ Docker authentication configured"
          else
            echo "❌ Docker authentication failed"
            exit 1
          fi
          
          # Test repository permissions
          echo "🔑 Testing repository permissions..."
          SERVICE_NAME="api-github-main"
          IMAGE_NAME="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/api-images/${SERVICE_NAME}:test"
          
          echo "🧪 Testing image push permissions with test image..."
          echo "FROM alpine:latest" > Dockerfile.test
          echo "RUN echo 'test'" >> Dockerfile.test
          
          if docker build -f Dockerfile.test -t ${IMAGE_NAME} . && docker push ${IMAGE_NAME}; then
            echo "✅ Successfully pushed test image - permissions are correct!"
            # Clean up test image
            gcloud artifacts docker images delete ${IMAGE_NAME} --quiet || echo "⚠️ Could not delete test image (this is okay)"
          else
            echo "❌ Failed to push test image - permission issue detected!"
            echo "🔍 Checking IAM permissions for service account..."
            
            # Get current service account
            CURRENT_SA=$(gcloud auth list --filter=status:ACTIVE --format="value(account)")
            echo "📋 Current service account: $CURRENT_SA"
            
            # Check IAM policy for the service account
            echo "🔍 IAM roles for service account:"
            gcloud projects get-iam-policy ${{ secrets.GCP_PROJECT_ID }} \
              --flatten="bindings[].members" \
              --format="table(bindings.role)" \
              --filter="bindings.members:$CURRENT_SA"
            
            exit 1
          fi
          
          # Clean up test files
          rm -f Dockerfile.test
          
          echo "=== ✅ ALL VALIDATIONS PASSED ==="

      - name: 🐳 Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
      
      - name: 🏗️ Build and Push Docker Image
        run: |
          cd apps/api/github
          
          # Use fixed service name for main deployment
          SERVICE_NAME="api-github-main"
          IMAGE_NAME="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/api-images/${SERVICE_NAME}:${{ github.sha }}"
          
          echo "🏷️ Building image: $IMAGE_NAME"
          echo "🔖 Service name: $SERVICE_NAME"
          
          # Build and push the image
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          
          # Store values for next step
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV
      
      - name: 🚀 Deploy to Cloud Run
        id: deploy
        run: |
          # Validate GitHub token secret before deployment
          if [ -z "${{ secrets.API_GITHUB_TOKEN }}" ]; then
            echo "❌ ERROR: API_GITHUB_TOKEN secret is not set!"
            echo "🔍 Please ensure the API_GITHUB_TOKEN secret is configured in repository settings"
            exit 1
          fi
          
          # Log token presence (first 4 characters for debugging)
          GITHUB_TOKEN_VALUE="${{ secrets.API_GITHUB_TOKEN }}"
          TOKEN_PREFIX=$(echo "$GITHUB_TOKEN_VALUE" | cut -c1-4)
          TOKEN_LENGTH=${#GITHUB_TOKEN_VALUE}
          echo "🔑 GitHub Token Debug: prefix='$TOKEN_PREFIX' length=$TOKEN_LENGTH"
          
          # Deploy main production service
          echo "🚀 Deploying main production service with name: $SERVICE_NAME"
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE_NAME \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --memory=512Mi \
            --cpu=1 \
            --min-instances=0 \
            --max-instances=10 \
            --timeout=60s \
            --concurrency=100 \
            --set-env-vars="NODE_ENV=production,GITHUB_TOKEN=${{ secrets.API_GITHUB_TOKEN }}"
          
          # Get the service URL
          SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --platform managed --region us-central1 --format 'value(status.url)')
          
          echo "🌐 Main production service deployed at: $SERVICE_URL"
          echo "deployment_url=$SERVICE_URL" >> $GITHUB_OUTPUT
          
          # Verify environment variables were set correctly
          echo "🔍 Verifying environment variables in deployed service..."
          gcloud run services describe $SERVICE_NAME --platform managed --region us-central1 --format="value(spec.template.spec.template.spec.containers[0].env[].name,spec.template.spec.template.spec.containers[0].env[].value)"
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: ✅ Validate API Deployment
        run: |
          API_URL="${{ steps.deploy.outputs.deployment_url }}"
          echo "🔍 Testing main production API at: $API_URL"
          
          # Test health endpoint with retry and validate response
          for i in {1..5}; do
            echo "🏥 Health check attempt $i/5..."
            
            # Get health response
            HEALTH_RESPONSE=$(curl -s -f "$API_URL/health" -m 15)
            CURL_EXIT_CODE=$?
            
            if [ $CURL_EXIT_CODE -eq 0 ]; then
              echo "✅ API responded successfully!"
              echo "📄 Health Response: $HEALTH_RESPONSE"
              
              # Parse JSON response and check GitHub token status
              TOKEN_STATUS=$(echo "$HEALTH_RESPONSE" | jq -r '.github_token.status // "unknown"')
              TOKEN_PRESENT=$(echo "$HEALTH_RESPONSE" | jq -r '.github_token.present // false')
              OVERALL_STATUS=$(echo "$HEALTH_RESPONSE" | jq -r '.status // "unknown"')
              
              echo "🔍 Overall Status: $OVERALL_STATUS"
              echo "🔑 Token Present: $TOKEN_PRESENT"
              echo "📋 Token Status: $TOKEN_STATUS"
              
              # Validate GitHub token is properly configured
              if [ "$TOKEN_STATUS" = "configured" ] && [ "$TOKEN_PRESENT" = "true" ]; then
                echo "✅ GitHub token is properly configured!"
                break
              else
                echo "❌ GitHub token is not properly configured!"
                echo "🔍 Expected: TOKEN_STATUS='configured' and TOKEN_PRESENT='true'"
                echo "🔍 Actual: TOKEN_STATUS='$TOKEN_STATUS' and TOKEN_PRESENT='$TOKEN_PRESENT'"
                
                if [ $i -eq 5 ]; then
                  echo "❌ GitHub token validation failed after 5 attempts"
                  exit 1
                fi
              fi
            else
              echo "❌ API health endpoint failed (HTTP error)"
              
              if [ $i -eq 5 ]; then
                echo "❌ API health check failed after 5 attempts"
                exit 1
              fi
            fi
            
            echo "⏳ Waiting 10 seconds before retry..."
            sleep 10
          done
          
          # Test CORS by making a preflight request
          echo "🌐 Testing CORS configuration..."
          CORS_RESPONSE=$(curl -s -X OPTIONS "$API_URL/health" \
            -H "Origin: https://odyssey-466315.web.app" \
            -H "Access-Control-Request-Method: GET" \
            -H "Access-Control-Request-Headers: Content-Type" \
            -w "%{http_code}" -o /dev/null)
          
          if [ "$CORS_RESPONSE" = "200" ]; then
            echo "✅ CORS configuration is working correctly!"
          else
            echo "⚠️ CORS preflight returned status: $CORS_RESPONSE"
            echo "🔍 This may indicate CORS issues with the frontend"
          fi
      
      - name: 📊 Deployment Summary
        run: |
          echo "🎯 Main Production API Deployment Complete!"
          echo "📍 URL: ${{ steps.deploy.outputs.deployment_url }}"
          echo "🏷️ Service: $SERVICE_NAME"
          echo "✅ Health check passed" 