name: Test API Main Deployment

on:
  workflow_call:
    inputs:
      api_deployment_url:
        required: true
        type: string

jobs:
  test-api:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🛒 Checkout Repository
        uses: actions/checkout@v4
      
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: e2e/package-lock.json
      
      - name: 📥 Install E2E Dependencies
        run: |
          cd e2e
          npm ci
      
      - name: 🔧 Build Observability Package
        run: |
          cd packages/observability
          npm ci
          npm run build
      
      - name: 🧪 Test API Health Check
        run: |
          echo "🏥 Testing main production API health at: ${{ inputs.api_deployment_url }}"
          
          # Test health endpoint with retry
          for i in {1..5}; do
            echo "🔍 Health check attempt $i/5..."
            if curl -f "${{ inputs.api_deployment_url }}/health" -m 15; then
              echo "✅ API is healthy!"
              break
            fi
            
            if [ $i -eq 5 ]; then
              echo "❌ API health check failed after 5 attempts"
              exit 1
            fi
            
            echo "⏳ Waiting 10 seconds..."
            sleep 10
          done
      
      - name: 🧪 Test API Endpoints
        run: |
          echo "🚀 Testing main production API endpoints..."
          
          # Test pull requests endpoint
          echo "📄 Testing pull requests endpoint..."
          for i in {1..3}; do
            echo "Pull requests test attempt $i/3..."
            
            if curl -f "${{ inputs.api_deployment_url }}/api/github/pull-requests/test" -m 15; then
              echo "✅ Pull requests endpoint is working!"
              break
            fi
            
            if [ $i -eq 3 ]; then
              echo "❌ Pull requests endpoint failed after 3 attempts"
              exit 1
            fi
            
            echo "⏳ Waiting 10 seconds..."
            sleep 10
          done
          
          echo "✅ All API endpoint tests passed!"
      
      - name: 🎯 Run API Integration Tests
        run: |
          echo "🧪 Running API integration tests..."
          cd e2e
          npm run test:api:production
        env:
          API_BASE_URL: ${{ inputs.api_deployment_url }}
          API_DEPLOYMENT_URL: ${{ inputs.api_deployment_url }}
          CLOUD_RUN_URL: ${{ inputs.api_deployment_url }}
        continue-on-error: true
      
      - name: 📊 API Test Summary
        run: |
          echo "🎯 Main Production API Testing Complete!"
          echo "📍 URL: ${{ inputs.api_deployment_url }}"
          echo "✅ Health checks passed"
          echo "✅ Endpoint tests passed"
          echo "📋 Integration tests completed"